
// Objective-C API for talking to the following Go packages
//
//	github.com/raedahgroup/mobilewallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobilewallet_FRAMEWORK_H__
#define __Mobilewallet_FRAMEWORK_H__

#include "Mobilewallet.objc.h"
#include "universe.objc.h"

#endif
