// Objective-C API for talking to github.com/raedahgroup/mobilewallet Go package.
//   gobind -lang=objc github.com/raedahgroup/mobilewallet
//
// File is generated by gobind. Do not edit.

#ifndef __Mobilewallet_H__
#define __Mobilewallet_H__

@import Foundation;
#include "Universe.objc.h"


@class MobilewalletAccount;
@class MobilewalletAccounts;
@class MobilewalletBalance;
@class MobilewalletDecodedInput;
@class MobilewalletDecodedOutput;
@class MobilewalletDecodedTransaction;
@class MobilewalletLibWallet;
@class MobilewalletTransaction;
@class MobilewalletTransactionCredit;
@class MobilewalletTransactionDebit;
@class MobilewalletUnsignedTransaction;
@protocol MobilewalletBlockNotificationError;
@class MobilewalletBlockNotificationError;
@protocol MobilewalletBlockScanResponse;
@class MobilewalletBlockScanResponse;
@protocol MobilewalletGetTransactionsResponse;
@class MobilewalletGetTransactionsResponse;
@protocol MobilewalletSpvSyncResponse;
@class MobilewalletSpvSyncResponse;
@protocol MobilewalletTransactionListener;
@class MobilewalletTransactionListener;

@protocol MobilewalletBlockNotificationError <NSObject>
- (void)onBlockNotificationError:(NSError*)err;
@end

@protocol MobilewalletBlockScanResponse <NSObject>
- (void)onEnd:(int32_t)height cancelled:(BOOL)cancelled;
- (void)onError:(int32_t)code message:(NSString*)message;
- (BOOL)onScan:(int32_t)rescannedThrough;
@end

@protocol MobilewalletGetTransactionsResponse <NSObject>
- (void)onResult:(NSString*)json;
@end

@protocol MobilewalletSpvSyncResponse <NSObject>
- (void)onDiscoveredAddresses:(BOOL)finished;
- (void)onFetchMissingCFilters:(int32_t)missingCFitlersStart missingCFitlersEnd:(int32_t)missingCFitlersEnd finished:(BOOL)finished;
- (void)onFetchedHeaders:(int32_t)fetchedHeadersCount lastHeaderTime:(int64_t)lastHeaderTime finished:(BOOL)finished;
- (void)onPeerConnected:(int32_t)peerCount;
- (void)onPeerDisconnected:(int32_t)peerCount;
- (void)onRescanProgress:(int32_t)rescannedThrough finished:(BOOL)finished;
- (void)onSyncError:(long)code err:(NSError*)err;
- (void)onSynced:(BOOL)synced;
@end

@protocol MobilewalletTransactionListener <NSObject>
- (void)onBlockAttached:(int32_t)height timestamp:(int64_t)timestamp;
- (void)onTransaction:(NSString*)transaction;
- (void)onTransactionConfirmed:(NSString*)hash height:(int32_t)height;
@end

@interface MobilewalletAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)number;
- (void)setNumber:(int32_t)v;
- (NSString*)name;
- (void)setName:(NSString*)v;
- (MobilewalletBalance*)balance;
- (void)setBalance:(MobilewalletBalance*)v;
- (int64_t)totalBalance;
- (void)setTotalBalance:(int64_t)v;
- (int32_t)externalKeyCount;
- (void)setExternalKeyCount:(int32_t)v;
- (int32_t)internalKeyCount;
- (void)setInternalKeyCount:(int32_t)v;
- (int32_t)importedKeyCount;
- (void)setImportedKeyCount:(int32_t)v;
@end

@interface MobilewalletAccounts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (long)count;
- (void)setCount:(long)v;
- (NSString*)errorMessage;
- (void)setErrorMessage:(NSString*)v;
- (long)errorCode;
- (void)setErrorCode:(long)v;
- (BOOL)errorOccurred;
- (void)setErrorOccurred:(BOOL)v;
// skipped field Accounts.Acc with unsupported type: *[]github.com/raedahgroup/mobilewallet.Account

- (NSData*)currentBlockHash;
- (void)setCurrentBlockHash:(NSData*)v;
- (int32_t)currentBlockHeight;
- (void)setCurrentBlockHeight:(int32_t)v;
@end

@interface MobilewalletBalance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int64_t)total;
- (void)setTotal:(int64_t)v;
- (int64_t)spendable;
- (void)setSpendable:(int64_t)v;
- (int64_t)immatureReward;
- (void)setImmatureReward:(int64_t)v;
- (int64_t)immatureStakeGeneration;
- (void)setImmatureStakeGeneration:(int64_t)v;
- (int64_t)lockedByTickets;
- (void)setLockedByTickets:(int64_t)v;
- (int64_t)votingAuthority;
- (void)setVotingAuthority:(int64_t)v;
- (int64_t)unConfirmed;
- (void)setUnConfirmed:(int64_t)v;
@end

@interface MobilewalletDecodedInput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)previousTransactionHash;
- (void)setPreviousTransactionHash:(NSString*)v;
- (int32_t)previousTransactionIndex;
- (void)setPreviousTransactionIndex:(int32_t)v;
- (int64_t)amountIn;
- (void)setAmountIn:(int64_t)v;
@end

@interface MobilewalletDecodedOutput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)index;
- (void)setIndex:(int32_t)v;
- (int64_t)value;
- (void)setValue:(int64_t)v;
- (int32_t)version;
- (void)setVersion:(int32_t)v;
- (BOOL)nullScript;
- (void)setNullScript:(BOOL)v;
// skipped field DecodedOutput.Addresses with unsupported type: []string

@end

@interface MobilewalletDecodedTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)hash;
- (void)setHash:(NSString*)v;
- (NSString*)type;
- (void)setType:(NSString*)v;
- (int32_t)version;
- (void)setVersion:(int32_t)v;
- (int32_t)lockTime;
- (void)setLockTime:(int32_t)v;
- (int32_t)expiry;
- (void)setExpiry:(int32_t)v;
// skipped field DecodedTransaction.Inputs with unsupported type: []github.com/raedahgroup/mobilewallet.DecodedInput

// skipped field DecodedTransaction.Outputs with unsupported type: []github.com/raedahgroup/mobilewallet.DecodedOutput

@end

@interface MobilewalletLibWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init:(NSString*)homeDir dbDriver:(NSString*)dbDriver;
- (NSString*)addressForAccount:(int32_t)account error:(NSError**)error;
- (NSString*)callJSONRPC:(NSString*)method args:(NSString*)args address:(NSString*)address username:(NSString*)username password:(NSString*)password caCert:(NSString*)caCert error:(NSError**)error;
- (BOOL)closeWallet:(NSError**)error;
- (MobilewalletUnsignedTransaction*)constructTransaction:(NSString*)destAddr amount:(int64_t)amount srcAccount:(int32_t)srcAccount requiredConfirmations:(int32_t)requiredConfirmations sendAll:(BOOL)sendAll error:(NSError**)error;
- (BOOL)createWallet:(NSString*)passphrase seedMnemonic:(NSString*)seedMnemonic error:(NSError**)error;
- (NSString*)decodeTransaction:(NSData*)txHash error:(NSError**)error;
- (BOOL)discoverActiveAddresses:(NSError**)error;
- (BOOL)fetchHeaders:(int32_t*)ret0_ error:(NSError**)error;
- (NSString*)generateSeed:(NSError**)error;
- (NSString*)getAccountByAddress:(NSString*)address;
- (NSString*)getAccountName:(int32_t)account;
- (NSString*)getAccounts:(int32_t)requiredConfirmations error:(NSError**)error;
- (int32_t)getBestBlock;
- (int64_t)getBestBlockTimeStamp;
/**
 * GetRecentTransactions fetches recent transaction and tries to return at most maximumRecentTransactions
 */
- (BOOL)getRecentTransactions:(id<MobilewalletGetTransactionsResponse>)response startHeight:(int32_t)startHeight maximumRecentTransactions:(long)maximumRecentTransactions error:(NSError**)error;
- (BOOL)getTransactions:(id<MobilewalletGetTransactionsResponse>)response error:(NSError**)error;
- (void)initLoader;
- (BOOL)isAddressMine:(NSString*)address;
- (BOOL)isAddressValid:(NSString*)address;
- (BOOL)isNetBackendNil;
- (BOOL)loadActiveDataFilters:(NSError**)error;
- (void)lockWallet;
- (BOOL)nextAccount:(NSString*)accountName privPass:(NSData*)privPass;
- (BOOL)openWallet:(NSError**)error;
- (BOOL)publishUnminedTransactions:(NSError**)error;
- (BOOL)renameAccount:(int32_t)accountNumber newName:(NSString*)newName error:(NSError**)error;
- (void)rescan:(int32_t)startHeight response:(id<MobilewalletBlockScanResponse>)response;
- (NSData*)rescanPoint;
- (void)runGC;
- (NSData*)sendTransaction:(NSData*)privPass destAddr:(NSString*)destAddr amount:(int64_t)amount srcAccount:(int32_t)srcAccount requiredConfs:(int32_t)requiredConfs sendAll:(BOOL)sendAll error:(NSError**)error;
- (void)setLogLevel:(NSString*)loglevel;
- (void)shutdown;
- (NSData*)signMessage:(NSData*)passphrase address:(NSString*)address message:(NSString*)message error:(NSError**)error;
- (BOOL)spendableForAccount:(int32_t)account requiredConfirmations:(int32_t)requiredConfirmations ret0_:(int64_t*)ret0_ error:(NSError**)error;
- (BOOL)spvSync:(id<MobilewalletSpvSyncResponse>)syncResponse peerAddresses:(NSString*)peerAddresses discoverAccounts:(BOOL)discoverAccounts privatePassphrase:(NSData*)privatePassphrase error:(NSError**)error;
- (BOOL)startRPCClient:(NSString*)rpcHost rpcUser:(NSString*)rpcUser rpcPass:(NSString*)rpcPass certs:(NSData*)certs error:(NSError**)error;
- (void)startSPVConnection:(NSString*)peerAddress;
- (BOOL)subscribeToBlockNotifications:(id<MobilewalletBlockNotificationError>)listener error:(NSError**)error;
- (void)transactionNotification:(id<MobilewalletTransactionListener>)listener;
- (BOOL)unlockWallet:(NSData*)privPass error:(NSError**)error;
- (BOOL)verifyMessage:(NSString*)address message:(NSString*)message signatureBase64:(NSString*)signatureBase64 ret0_:(BOOL*)ret0_ error:(NSError**)error;
- (BOOL)verifySeed:(NSString*)seedMnemonic;
@end

/**
 * Direction
0: Sent
1: Received
2: Transfered
 */
@interface MobilewalletTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)hash;
- (void)setHash:(NSString*)v;
- (NSString*)raw;
- (void)setRaw:(NSString*)v;
- (NSData*)transaction;
- (void)setTransaction:(NSData*)v;
- (int64_t)fee;
- (void)setFee:(int64_t)v;
- (int64_t)timestamp;
- (void)setTimestamp:(int64_t)v;
- (NSString*)type;
- (void)setType:(NSString*)v;
- (int64_t)amount;
- (void)setAmount:(int64_t)v;
- (NSString*)status;
- (void)setStatus:(NSString*)v;
- (int32_t)height;
- (void)setHeight:(int32_t)v;
- (int32_t)direction;
- (void)setDirection:(int32_t)v;
// skipped field Transaction.Debits with unsupported type: *[]github.com/raedahgroup/mobilewallet.TransactionDebit

// skipped field Transaction.Credits with unsupported type: *[]github.com/raedahgroup/mobilewallet.TransactionCredit

@end

@interface MobilewalletTransactionCredit : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)index;
- (void)setIndex:(int32_t)v;
- (int32_t)account;
- (void)setAccount:(int32_t)v;
- (BOOL)internal;
- (void)setInternal:(BOOL)v;
- (int64_t)amount;
- (void)setAmount:(int64_t)v;
- (NSString*)address;
- (void)setAddress:(NSString*)v;
@end

@interface MobilewalletTransactionDebit : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)index;
- (void)setIndex:(int32_t)v;
- (int32_t)previousAccount;
- (void)setPreviousAccount:(int32_t)v;
- (int64_t)previousAmount;
- (void)setPreviousAmount:(int64_t)v;
- (NSString*)accountName;
- (void)setAccountName:(NSString*)v;
@end

@interface MobilewalletUnsignedTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)unsignedTransaction;
- (void)setUnsignedTransaction:(NSData*)v;
- (long)estimatedSignedSize;
- (void)setEstimatedSignedSize:(long)v;
- (long)changeIndex;
- (void)setChangeIndex:(long)v;
- (int64_t)totalOutputAmount;
- (void)setTotalOutputAmount:(int64_t)v;
- (int64_t)totalPreviousOutputAmount;
- (void)setTotalPreviousOutputAmount:(int64_t)v;
@end

FOUNDATION_EXPORT NSString* const MobilewalletErrEmptySeed;
FOUNDATION_EXPORT NSString* const MobilewalletErrInsufficientBalance;
FOUNDATION_EXPORT NSString* const MobilewalletErrInvalid;
FOUNDATION_EXPORT NSString* const MobilewalletErrInvalidAddress;
FOUNDATION_EXPORT NSString* const MobilewalletErrInvalidPassphrase;
FOUNDATION_EXPORT NSString* const MobilewalletErrNotConnected;
FOUNDATION_EXPORT NSString* const MobilewalletErrNotExist;
FOUNDATION_EXPORT NSString* const MobilewalletErrPassphraseRequired;
FOUNDATION_EXPORT NSString* const MobilewalletErrWalletNotLoaded;

FOUNDATION_EXPORT int64_t MobilewalletAmountAtom(double f);

FOUNDATION_EXPORT double MobilewalletAmountCoin(int64_t amount);

FOUNDATION_EXPORT NSData* MobilewalletDecodeBase64(NSString* base64Text, NSError** error);

FOUNDATION_EXPORT NSString* MobilewalletEncodeBase64(NSData* text);

FOUNDATION_EXPORT NSString* MobilewalletEncodeHex(NSData* hexBytes);

FOUNDATION_EXPORT MobilewalletLibWallet* MobilewalletNewLibWallet(NSString* homeDir, NSString* dbDriver);

FOUNDATION_EXPORT NSString* MobilewalletNormalizeAddress(NSString* addr, NSString* defaultPort, NSError** error);

@class MobilewalletBlockNotificationError;

@class MobilewalletBlockScanResponse;

@class MobilewalletGetTransactionsResponse;

@class MobilewalletSpvSyncResponse;

@class MobilewalletTransactionListener;

@interface MobilewalletBlockNotificationError : NSObject <goSeqRefInterface, MobilewalletBlockNotificationError> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onBlockNotificationError:(NSError*)err;
@end

@interface MobilewalletBlockScanResponse : NSObject <goSeqRefInterface, MobilewalletBlockScanResponse> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onEnd:(int32_t)height cancelled:(BOOL)cancelled;
- (void)onError:(int32_t)code message:(NSString*)message;
- (BOOL)onScan:(int32_t)rescannedThrough;
@end

@interface MobilewalletGetTransactionsResponse : NSObject <goSeqRefInterface, MobilewalletGetTransactionsResponse> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onResult:(NSString*)json;
@end

@interface MobilewalletSpvSyncResponse : NSObject <goSeqRefInterface, MobilewalletSpvSyncResponse> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onDiscoveredAddresses:(BOOL)finished;
- (void)onFetchMissingCFilters:(int32_t)missingCFitlersStart missingCFitlersEnd:(int32_t)missingCFitlersEnd finished:(BOOL)finished;
- (void)onFetchedHeaders:(int32_t)fetchedHeadersCount lastHeaderTime:(int64_t)lastHeaderTime finished:(BOOL)finished;
- (void)onPeerConnected:(int32_t)peerCount;
- (void)onPeerDisconnected:(int32_t)peerCount;
- (void)onRescanProgress:(int32_t)rescannedThrough finished:(BOOL)finished;
/**
 * 	* Handled Error Codes
	* -1 - Unexpected Error
	*  1 - Context Canceled
	*  2 - Deadline Exceeded
	*  3 - Invalid Address
 */
- (void)onSyncError:(long)code err:(NSError*)err;
- (void)onSynced:(BOOL)synced;
@end

@interface MobilewalletTransactionListener : NSObject <goSeqRefInterface, MobilewalletTransactionListener> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onBlockAttached:(int32_t)height timestamp:(int64_t)timestamp;
- (void)onTransaction:(NSString*)transaction;
- (void)onTransactionConfirmed:(NSString*)hash height:(int32_t)height;
@end

#endif
