// Objective-C API for talking to mobilewallet Go package.
//   gobind -lang=objc mobilewallet
//
// File is generated by gobind. Do not edit.

#ifndef __Mobilewallet_H__
#define __Mobilewallet_H__

@import Foundation;
#include "Universe.objc.h"


@class MobilewalletAccount;
@class MobilewalletAccounts;
@class MobilewalletBalance;
@class MobilewalletConstructTxResponse;
@class MobilewalletLibWallet;
@class MobilewalletTransaction;
@class MobilewalletTransactionCredit;
@class MobilewalletTransactionDebit;
@protocol MobilewalletBlockNotificationError;
@class MobilewalletBlockNotificationError;
@protocol MobilewalletBlockScanResponse;
@class MobilewalletBlockScanResponse;
@protocol MobilewalletGetTransactionsResponse;
@class MobilewalletGetTransactionsResponse;
@protocol MobilewalletTransactionListener;
@class MobilewalletTransactionListener;

@protocol MobilewalletBlockNotificationError <NSObject>
- (void)onBlockNotificationError:(NSError*)err;
@end

@protocol MobilewalletBlockScanResponse <NSObject>
- (void)onEnd:(int32_t)height cancelled:(BOOL)cancelled;
- (void)onError:(int32_t)code message:(NSString*)message;
- (BOOL)onScan:(int32_t)rescannedThrough;
@end

@protocol MobilewalletGetTransactionsResponse <NSObject>
- (void)onResult:(NSString*)json;
@end

@protocol MobilewalletTransactionListener <NSObject>
- (void)onTransaction:(NSString*)transaction;
@end

@interface MobilewalletAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)number;
- (void)setNumber:(int32_t)v;
- (NSString*)name;
- (void)setName:(NSString*)v;
- (MobilewalletBalance*)balance;
- (void)setBalance:(MobilewalletBalance*)v;
- (int64_t)totalBalance;
- (void)setTotalBalance:(int64_t)v;
- (int32_t)externalKeyCount;
- (void)setExternalKeyCount:(int32_t)v;
- (int32_t)internalKeyCount;
- (void)setInternalKeyCount:(int32_t)v;
- (int32_t)importedKeyCount;
- (void)setImportedKeyCount:(int32_t)v;
@end

@interface MobilewalletAccounts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (long)count;
- (void)setCount:(long)v;
- (NSString*)errorMessage;
- (void)setErrorMessage:(NSString*)v;
- (long)errorCode;
- (void)setErrorCode:(long)v;
- (BOOL)errorOccurred;
- (void)setErrorOccurred:(BOOL)v;
// skipped field Accounts.Acc with unsupported type: *[]mobilewallet.Account

- (NSData*)currentBlockHash;
- (void)setCurrentBlockHash:(NSData*)v;
- (int32_t)currentBlockHeight;
- (void)setCurrentBlockHeight:(int32_t)v;
@end

@interface MobilewalletBalance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int64_t)total;
- (void)setTotal:(int64_t)v;
- (int64_t)spendable;
- (void)setSpendable:(int64_t)v;
- (int64_t)immatureReward;
- (void)setImmatureReward:(int64_t)v;
- (int64_t)immatureStakeGeneration;
- (void)setImmatureStakeGeneration:(int64_t)v;
- (int64_t)lockedByTickets;
- (void)setLockedByTickets:(int64_t)v;
- (int64_t)votingAuthority;
- (void)setVotingAuthority:(int64_t)v;
- (int64_t)unConfirmed;
- (void)setUnConfirmed:(int64_t)v;
@end

@interface MobilewalletConstructTxResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)estimatedSignedSize;
- (void)setEstimatedSignedSize:(int32_t)v;
- (int64_t)totalOutputAmount;
- (void)setTotalOutputAmount:(int64_t)v;
- (int64_t)totalPreviousOutputAmount;
- (void)setTotalPreviousOutputAmount:(int64_t)v;
- (NSData*)unsignedTransaction;
- (void)setUnsignedTransaction:(NSData*)v;
@end

@interface MobilewalletLibWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init:(NSString*)homeDir;
- (NSString*)addressForAccount:(int32_t)account error:(NSError**)error;
- (MobilewalletConstructTxResponse*)constructTransaction:(NSString*)destAddr amount:(int64_t)amount srcAccount:(int32_t)srcAccount requiredConfirmations:(int32_t)requiredConfirmations error:(NSError**)error;
- (BOOL)createWallet:(NSString*)passphrase seedMnemonic:(NSString*)seedMnemonic error:(NSError**)error;
- (BOOL)discoverActiveAddresses:(BOOL)discoverAccounts privPass:(NSData*)privPass error:(NSError**)error;
- (BOOL)fetchHeaders:(int32_t*)ret0_ error:(NSError**)error;
- (NSString*)generateSeed:(NSError**)error;
- (NSString*)getAccountName:(int32_t)account;
- (NSString*)getAccounts:(NSError**)error;
- (int32_t)getBestBlock;
- (int64_t)getBestBlockTimeStamp;
- (BOOL)getTransactions:(id<MobilewalletGetTransactionsResponse>)response error:(NSError**)error;
- (void)initLoader;
- (BOOL)isAddressMine:(NSString*)address;
- (BOOL)isNetBackendNil;
- (BOOL)loadActiveDataFilters:(NSError**)error;
- (BOOL)nextAccount:(NSString*)accountName privPass:(NSData*)privPass;
- (BOOL)openWallet:(NSError**)error;
- (NSData*)publishTransaction:(NSData*)signedTransaction error:(NSError**)error;
- (BOOL)publishUnminedTransactions:(NSError**)error;
- (void)rescan:(int32_t)startHeight response:(id<MobilewalletBlockScanResponse>)response;
- (NSData*)signTransaction:(NSData*)rawTransaction privPass:(NSData*)privPass error:(NSError**)error;
- (BOOL)spendableForAccount:(int32_t)account requiredConfirmations:(int32_t)requiredConfirmations ret0_:(int64_t*)ret0_ error:(NSError**)error;
- (BOOL)startRPCClient:(NSString*)rpcHost rpcUser:(NSString*)rpcUser rpcPass:(NSString*)rpcPass certs:(NSData*)certs error:(NSError**)error;
- (BOOL)subscribeToBlockNotifications:(id<MobilewalletBlockNotificationError>)listener error:(NSError**)error;
- (void)transactionNotification:(id<MobilewalletTransactionListener>)listener;
- (BOOL)verifySeed:(NSString*)seedMnemonic;
@end

@interface MobilewalletTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)hash;
- (void)setHash:(NSString*)v;
- (NSData*)transaction;
- (void)setTransaction:(NSData*)v;
- (int64_t)fee;
- (void)setFee:(int64_t)v;
- (int64_t)timestamp;
- (void)setTimestamp:(int64_t)v;
- (NSString*)type;
- (void)setType:(NSString*)v;
- (int64_t)amount;
- (void)setAmount:(int64_t)v;
- (NSString*)status;
- (void)setStatus:(NSString*)v;
- (int32_t)height;
- (void)setHeight:(int32_t)v;
// skipped field Transaction.Debits with unsupported type: *[]mobilewallet.TransactionDebit

// skipped field Transaction.Credits with unsupported type: *[]mobilewallet.TransactionCredit

@end

@interface MobilewalletTransactionCredit : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)index;
- (void)setIndex:(int32_t)v;
- (int32_t)account;
- (void)setAccount:(int32_t)v;
- (BOOL)internal;
- (void)setInternal:(BOOL)v;
- (int64_t)amount;
- (void)setAmount:(int64_t)v;
- (NSString*)address;
- (void)setAddress:(NSString*)v;
@end

@interface MobilewalletTransactionDebit : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int32_t)index;
- (void)setIndex:(int32_t)v;
- (int32_t)previousAccount;
- (void)setPreviousAccount:(int32_t)v;
- (int64_t)previousAmount;
- (void)setPreviousAmount:(int64_t)v;
- (NSString*)accountName;
- (void)setAccountName:(NSString*)v;
@end

FOUNDATION_EXPORT MobilewalletLibWallet* MobilewalletNewLibWallet(NSString* homeDir);

FOUNDATION_EXPORT NSString* MobilewalletNormalizeAddress(NSString* addr, NSString* defaultPort, NSError** error);

@class MobilewalletBlockNotificationError;

@class MobilewalletBlockScanResponse;

@class MobilewalletGetTransactionsResponse;

@class MobilewalletTransactionListener;

@interface MobilewalletBlockNotificationError : NSObject <goSeqRefInterface, MobilewalletBlockNotificationError> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onBlockNotificationError:(NSError*)err;
@end

@interface MobilewalletBlockScanResponse : NSObject <goSeqRefInterface, MobilewalletBlockScanResponse> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onEnd:(int32_t)height cancelled:(BOOL)cancelled;
- (void)onError:(int32_t)code message:(NSString*)message;
- (BOOL)onScan:(int32_t)rescannedThrough;
@end

@interface MobilewalletGetTransactionsResponse : NSObject <goSeqRefInterface, MobilewalletGetTransactionsResponse> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onResult:(NSString*)json;
@end

@interface MobilewalletTransactionListener : NSObject <goSeqRefInterface, MobilewalletTransactionListener> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onTransaction:(NSString*)transaction;
@end

#endif
