
// Objective-C API for talking to the following Go packages
//
//	wallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Wallet_FRAMEWORK_H__
#define __Wallet_FRAMEWORK_H__

#include "Wallet.objc.h"
#include "universe.objc.h"

#endif
